// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: ai/v1/agent.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentServiceRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceRunRequest) Reset() {
	*x = AgentServiceRunRequest{}
	mi := &file_ai_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceRunRequest) ProtoMessage() {}

func (x *AgentServiceRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceRunRequest.ProtoReflect.Descriptor instead.
func (*AgentServiceRunRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentServiceRunRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AgentServiceRunRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AgentServiceRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceRunResponse) Reset() {
	*x = AgentServiceRunResponse{}
	mi := &file_ai_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceRunResponse) ProtoMessage() {}

func (x *AgentServiceRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceRunResponse.ProtoReflect.Descriptor instead.
func (*AgentServiceRunResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentServiceRunResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_ai_v1_agent_proto protoreflect.FileDescriptor

const file_ai_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x11ai/v1/agent.proto\x12\x0eflowmind.ai.v1\x1a\x12ai/v1/common.proto\"\x8b\x01\n" +
	"\x16AgentServiceRunRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.flowmind.ai.v1.RequestContextR\acontext\x127\n" +
	"\bmessages\x18\x02 \x03(\v2\x1b.flowmind.ai.v1.ChatMessageR\bmessages\"P\n" +
	"\x17AgentServiceRunResponse\x125\n" +
	"\amessage\x18\x01 \x01(\v2\x1b.flowmind.ai.v1.ChatMessageR\amessage2f\n" +
	"\fAgentService\x12V\n" +
	"\x03Run\x12&.flowmind.ai.v1.AgentServiceRunRequest\x1a'.flowmind.ai.v1.AgentServiceRunResponseB9Z7ai-flowmind/services/go-api/internal/grpcclient/pb;aiv1b\x06proto3"

var (
	file_ai_v1_agent_proto_rawDescOnce sync.Once
	file_ai_v1_agent_proto_rawDescData []byte
)

func file_ai_v1_agent_proto_rawDescGZIP() []byte {
	file_ai_v1_agent_proto_rawDescOnce.Do(func() {
		file_ai_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_agent_proto_rawDesc), len(file_ai_v1_agent_proto_rawDesc)))
	})
	return file_ai_v1_agent_proto_rawDescData
}

var file_ai_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_v1_agent_proto_goTypes = []any{
	(*AgentServiceRunRequest)(nil),  // 0: flowmind.ai.v1.AgentServiceRunRequest
	(*AgentServiceRunResponse)(nil), // 1: flowmind.ai.v1.AgentServiceRunResponse
	(*RequestContext)(nil),          // 2: flowmind.ai.v1.RequestContext
	(*ChatMessage)(nil),             // 3: flowmind.ai.v1.ChatMessage
}
var file_ai_v1_agent_proto_depIdxs = []int32{
	2, // 0: flowmind.ai.v1.AgentServiceRunRequest.context:type_name -> flowmind.ai.v1.RequestContext
	3, // 1: flowmind.ai.v1.AgentServiceRunRequest.messages:type_name -> flowmind.ai.v1.ChatMessage
	3, // 2: flowmind.ai.v1.AgentServiceRunResponse.message:type_name -> flowmind.ai.v1.ChatMessage
	0, // 3: flowmind.ai.v1.AgentService.Run:input_type -> flowmind.ai.v1.AgentServiceRunRequest
	1, // 4: flowmind.ai.v1.AgentService.Run:output_type -> flowmind.ai.v1.AgentServiceRunResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ai_v1_agent_proto_init() }
func file_ai_v1_agent_proto_init() {
	if File_ai_v1_agent_proto != nil {
		return
	}
	file_ai_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_agent_proto_rawDesc), len(file_ai_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_agent_proto_goTypes,
		DependencyIndexes: file_ai_v1_agent_proto_depIdxs,
		MessageInfos:      file_ai_v1_agent_proto_msgTypes,
	}.Build()
	File_ai_v1_agent_proto = out.File
	file_ai_v1_agent_proto_goTypes = nil
	file_ai_v1_agent_proto_depIdxs = nil
}
