// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: ai/v1/chat.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Context         *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Messages        []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxOutputTokens int32                  `protobuf:"varint,3,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	Temperature     float64                `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_ai_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CompleteRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompleteRequest) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *CompleteRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Usage         *TokenUsage            `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_ai_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CompleteResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CompleteResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *CompleteResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type CompleteStreamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Context         *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Messages        []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxOutputTokens int32                  `protobuf:"varint,3,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	Temperature     float64                `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteStreamRequest) Reset() {
	*x = CompleteStreamRequest{}
	mi := &file_ai_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteStreamRequest) ProtoMessage() {}

func (x *CompleteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteStreamRequest.ProtoReflect.Descriptor instead.
func (*CompleteStreamRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteStreamRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CompleteStreamRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompleteStreamRequest) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *CompleteStreamRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type CompleteStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         *ContentPart           `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	ModelName     string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Usage         *TokenUsage            `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteStreamResponse) Reset() {
	*x = CompleteStreamResponse{}
	mi := &file_ai_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteStreamResponse) ProtoMessage() {}

func (x *CompleteStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteStreamResponse.ProtoReflect.Descriptor instead.
func (*CompleteStreamResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteStreamResponse) GetDelta() *ContentPart {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *CompleteStreamResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *CompleteStreamResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CompleteStreamResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

var File_ai_v1_chat_proto protoreflect.FileDescriptor

const file_ai_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x10ai/v1/chat.proto\x12\x0eflowmind.ai.v1\x1a\x12ai/v1/common.proto\"\xd2\x01\n" +
	"\x0fCompleteRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.flowmind.ai.v1.RequestContextR\acontext\x127\n" +
	"\bmessages\x18\x02 \x03(\v2\x1b.flowmind.ai.v1.ChatMessageR\bmessages\x12*\n" +
	"\x11max_output_tokens\x18\x03 \x01(\x05R\x0fmaxOutputTokens\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\"\xb9\x01\n" +
	"\x10CompleteResponse\x125\n" +
	"\amessage\x18\x01 \x01(\v2\x1b.flowmind.ai.v1.ChatMessageR\amessage\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x120\n" +
	"\x05usage\x18\x03 \x01(\v2\x1a.flowmind.ai.v1.TokenUsageR\x05usage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\"\xd8\x01\n" +
	"\x15CompleteStreamRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.flowmind.ai.v1.RequestContextR\acontext\x127\n" +
	"\bmessages\x18\x02 \x03(\v2\x1b.flowmind.ai.v1.ChatMessageR\bmessages\x12*\n" +
	"\x11max_output_tokens\x18\x03 \x01(\x05R\x0fmaxOutputTokens\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\"\xb0\x01\n" +
	"\x16CompleteStreamResponse\x121\n" +
	"\x05delta\x18\x01 \x01(\v2\x1b.flowmind.ai.v1.ContentPartR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x120\n" +
	"\x05usage\x18\x04 \x01(\v2\x1a.flowmind.ai.v1.TokenUsageR\x05usage2\xbf\x01\n" +
	"\vChatService\x12M\n" +
	"\bComplete\x12\x1f.flowmind.ai.v1.CompleteRequest\x1a .flowmind.ai.v1.CompleteResponse\x12a\n" +
	"\x0eCompleteStream\x12%.flowmind.ai.v1.CompleteStreamRequest\x1a&.flowmind.ai.v1.CompleteStreamResponse0\x01B9Z7ai-flowmind/services/go-api/internal/grpcclient/pb;aiv1b\x06proto3"

var (
	file_ai_v1_chat_proto_rawDescOnce sync.Once
	file_ai_v1_chat_proto_rawDescData []byte
)

func file_ai_v1_chat_proto_rawDescGZIP() []byte {
	file_ai_v1_chat_proto_rawDescOnce.Do(func() {
		file_ai_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_chat_proto_rawDesc), len(file_ai_v1_chat_proto_rawDesc)))
	})
	return file_ai_v1_chat_proto_rawDescData
}

var file_ai_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ai_v1_chat_proto_goTypes = []any{
	(*CompleteRequest)(nil),        // 0: flowmind.ai.v1.CompleteRequest
	(*CompleteResponse)(nil),       // 1: flowmind.ai.v1.CompleteResponse
	(*CompleteStreamRequest)(nil),  // 2: flowmind.ai.v1.CompleteStreamRequest
	(*CompleteStreamResponse)(nil), // 3: flowmind.ai.v1.CompleteStreamResponse
	(*RequestContext)(nil),         // 4: flowmind.ai.v1.RequestContext
	(*ChatMessage)(nil),            // 5: flowmind.ai.v1.ChatMessage
	(*TokenUsage)(nil),             // 6: flowmind.ai.v1.TokenUsage
	(*ContentPart)(nil),            // 7: flowmind.ai.v1.ContentPart
}
var file_ai_v1_chat_proto_depIdxs = []int32{
	4,  // 0: flowmind.ai.v1.CompleteRequest.context:type_name -> flowmind.ai.v1.RequestContext
	5,  // 1: flowmind.ai.v1.CompleteRequest.messages:type_name -> flowmind.ai.v1.ChatMessage
	5,  // 2: flowmind.ai.v1.CompleteResponse.message:type_name -> flowmind.ai.v1.ChatMessage
	6,  // 3: flowmind.ai.v1.CompleteResponse.usage:type_name -> flowmind.ai.v1.TokenUsage
	4,  // 4: flowmind.ai.v1.CompleteStreamRequest.context:type_name -> flowmind.ai.v1.RequestContext
	5,  // 5: flowmind.ai.v1.CompleteStreamRequest.messages:type_name -> flowmind.ai.v1.ChatMessage
	7,  // 6: flowmind.ai.v1.CompleteStreamResponse.delta:type_name -> flowmind.ai.v1.ContentPart
	6,  // 7: flowmind.ai.v1.CompleteStreamResponse.usage:type_name -> flowmind.ai.v1.TokenUsage
	0,  // 8: flowmind.ai.v1.ChatService.Complete:input_type -> flowmind.ai.v1.CompleteRequest
	2,  // 9: flowmind.ai.v1.ChatService.CompleteStream:input_type -> flowmind.ai.v1.CompleteStreamRequest
	1,  // 10: flowmind.ai.v1.ChatService.Complete:output_type -> flowmind.ai.v1.CompleteResponse
	3,  // 11: flowmind.ai.v1.ChatService.CompleteStream:output_type -> flowmind.ai.v1.CompleteStreamResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ai_v1_chat_proto_init() }
func file_ai_v1_chat_proto_init() {
	if File_ai_v1_chat_proto != nil {
		return
	}
	file_ai_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_chat_proto_rawDesc), len(file_ai_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_chat_proto_goTypes,
		DependencyIndexes: file_ai_v1_chat_proto_depIdxs,
		MessageInfos:      file_ai_v1_chat_proto_msgTypes,
	}.Build()
	File_ai_v1_chat_proto = out.File
	file_ai_v1_chat_proto_goTypes = nil
	file_ai_v1_chat_proto_depIdxs = nil
}
