// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: ai/v1/common.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRole int32

const (
	MessageRole_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_MESSAGE_ROLE_SYSTEM      MessageRole = 1
	MessageRole_MESSAGE_ROLE_USER        MessageRole = 2
	MessageRole_MESSAGE_ROLE_ASSISTANT   MessageRole = 3
	MessageRole_MESSAGE_ROLE_TOOL        MessageRole = 4
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "MESSAGE_ROLE_UNSPECIFIED",
		1: "MESSAGE_ROLE_SYSTEM",
		2: "MESSAGE_ROLE_USER",
		3: "MESSAGE_ROLE_ASSISTANT",
		4: "MESSAGE_ROLE_TOOL",
	}
	MessageRole_value = map[string]int32{
		"MESSAGE_ROLE_UNSPECIFIED": 0,
		"MESSAGE_ROLE_SYSTEM":      1,
		"MESSAGE_ROLE_USER":        2,
		"MESSAGE_ROLE_ASSISTANT":   3,
		"MESSAGE_ROLE_TOOL":        4,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_common_proto_enumTypes[0].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_ai_v1_common_proto_enumTypes[0]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_common_proto_rawDescGZIP(), []int{0}
}

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_PENDING     MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_COMPLETED   MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_FAILED      MessageStatus = 3
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_PENDING",
		2: "MESSAGE_STATUS_COMPLETED",
		3: "MESSAGE_STATUS_FAILED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_PENDING":     1,
		"MESSAGE_STATUS_COMPLETED":   2,
		"MESSAGE_STATUS_FAILED":      3,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_common_proto_enumTypes[1].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_ai_v1_common_proto_enumTypes[1]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_common_proto_rawDescGZIP(), []int{1}
}

type RequestContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId        string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	OwnerKey       string                 `protobuf:"bytes,4,opt,name=owner_key,json=ownerKey,proto3" json:"owner_key,omitempty"`
	ModelProfile   string                 `protobuf:"bytes,5,opt,name=model_profile,json=modelProfile,proto3" json:"model_profile,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_ai_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_ai_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RequestContext) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RequestContext) GetOwnerKey() string {
	if x != nil {
		return x.OwnerKey
	}
	return ""
}

func (x *RequestContext) GetModelProfile() string {
	if x != nil {
		return x.ModelProfile
	}
	return ""
}

type TextPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPart) Reset() {
	*x = TextPart{}
	mi := &file_ai_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPart) ProtoMessage() {}

func (x *TextPart) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPart.ProtoReflect.Descriptor instead.
func (*TextPart) Descriptor() ([]byte, []int) {
	return file_ai_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *TextPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ImagePart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePart) Reset() {
	*x = ImagePart{}
	mi := &file_ai_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePart) ProtoMessage() {}

func (x *ImagePart) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePart.ProtoReflect.Descriptor instead.
func (*ImagePart) Descriptor() ([]byte, []int) {
	return file_ai_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ImagePart) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ImagePart) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type ContentPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*ContentPart_Text
	//	*ContentPart_Image
	Part          isContentPart_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPart) Reset() {
	*x = ContentPart{}
	mi := &file_ai_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPart) ProtoMessage() {}

func (x *ContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPart.ProtoReflect.Descriptor instead.
func (*ContentPart) Descriptor() ([]byte, []int) {
	return file_ai_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *ContentPart) GetPart() isContentPart_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *ContentPart) GetText() *TextPart {
	if x != nil {
		if x, ok := x.Part.(*ContentPart_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ContentPart) GetImage() *ImagePart {
	if x != nil {
		if x, ok := x.Part.(*ContentPart_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isContentPart_Part interface {
	isContentPart_Part()
}

type ContentPart_Text struct {
	Text *TextPart `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentPart_Image struct {
	Image *ImagePart `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*ContentPart_Text) isContentPart_Part() {}

func (*ContentPart_Image) isContentPart_Part() {}

type ChatMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role            MessageRole            `protobuf:"varint,2,opt,name=role,proto3,enum=flowmind.ai.v1.MessageRole" json:"role,omitempty"`
	Content         []*ContentPart         `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	Status          MessageStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=flowmind.ai.v1.MessageStatus" json:"status,omitempty"`
	ClientMessageId string                 `protobuf:"bytes,5,opt,name=client_message_id,json=clientMessageId,proto3" json:"client_message_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_ai_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_ai_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetContent() []*ContentPart {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatMessage) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *ChatMessage) GetClientMessageId() string {
	if x != nil {
		return x.ClientMessageId
	}
	return ""
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_ai_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_ai_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_ai_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_ai_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_ai_v1_common_proto protoreflect.FileDescriptor

const file_ai_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x12ai/v1/common.proto\x12\x0eflowmind.ai.v1\"\xb5\x01\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\towner_key\x18\x04 \x01(\tR\bownerKey\x12#\n" +
	"\rmodel_profile\x18\x05 \x01(\tR\fmodelProfile\"\x1e\n" +
	"\bTextPart\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"G\n" +
	"\tImagePart\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"x\n" +
	"\vContentPart\x12.\n" +
	"\x04text\x18\x01 \x01(\v2\x18.flowmind.ai.v1.TextPartH\x00R\x04text\x121\n" +
	"\x05image\x18\x02 \x01(\v2\x19.flowmind.ai.v1.ImagePartH\x00R\x05imageB\x06\n" +
	"\x04part\"\xe8\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1b.flowmind.ai.v1.MessageRoleR\x04role\x125\n" +
	"\acontent\x18\x03 \x03(\v2\x1b.flowmind.ai.v1.ContentPartR\acontent\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.flowmind.ai.v1.MessageStatusR\x06status\x12*\n" +
	"\x11client_message_id\x18\x05 \x01(\tR\x0fclientMessageId\"\x81\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"Y\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable*\x8e\x01\n" +
	"\vMessageRole\x12\x1c\n" +
	"\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_ROLE_SYSTEM\x10\x01\x12\x15\n" +
	"\x11MESSAGE_ROLE_USER\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_ROLE_ASSISTANT\x10\x03\x12\x15\n" +
	"\x11MESSAGE_ROLE_TOOL\x10\x04*\x84\x01\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15MESSAGE_STATUS_FAILED\x10\x03B9Z7ai-flowmind/services/go-api/internal/grpcclient/pb;aiv1b\x06proto3"

var (
	file_ai_v1_common_proto_rawDescOnce sync.Once
	file_ai_v1_common_proto_rawDescData []byte
)

func file_ai_v1_common_proto_rawDescGZIP() []byte {
	file_ai_v1_common_proto_rawDescOnce.Do(func() {
		file_ai_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_common_proto_rawDesc), len(file_ai_v1_common_proto_rawDesc)))
	})
	return file_ai_v1_common_proto_rawDescData
}

var file_ai_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ai_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ai_v1_common_proto_goTypes = []any{
	(MessageRole)(0),       // 0: flowmind.ai.v1.MessageRole
	(MessageStatus)(0),     // 1: flowmind.ai.v1.MessageStatus
	(*RequestContext)(nil), // 2: flowmind.ai.v1.RequestContext
	(*TextPart)(nil),       // 3: flowmind.ai.v1.TextPart
	(*ImagePart)(nil),      // 4: flowmind.ai.v1.ImagePart
	(*ContentPart)(nil),    // 5: flowmind.ai.v1.ContentPart
	(*ChatMessage)(nil),    // 6: flowmind.ai.v1.ChatMessage
	(*TokenUsage)(nil),     // 7: flowmind.ai.v1.TokenUsage
	(*ErrorDetail)(nil),    // 8: flowmind.ai.v1.ErrorDetail
}
var file_ai_v1_common_proto_depIdxs = []int32{
	3, // 0: flowmind.ai.v1.ContentPart.text:type_name -> flowmind.ai.v1.TextPart
	4, // 1: flowmind.ai.v1.ContentPart.image:type_name -> flowmind.ai.v1.ImagePart
	0, // 2: flowmind.ai.v1.ChatMessage.role:type_name -> flowmind.ai.v1.MessageRole
	5, // 3: flowmind.ai.v1.ChatMessage.content:type_name -> flowmind.ai.v1.ContentPart
	1, // 4: flowmind.ai.v1.ChatMessage.status:type_name -> flowmind.ai.v1.MessageStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ai_v1_common_proto_init() }
func file_ai_v1_common_proto_init() {
	if File_ai_v1_common_proto != nil {
		return
	}
	file_ai_v1_common_proto_msgTypes[3].OneofWrappers = []any{
		(*ContentPart_Text)(nil),
		(*ContentPart_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_common_proto_rawDesc), len(file_ai_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_v1_common_proto_goTypes,
		DependencyIndexes: file_ai_v1_common_proto_depIdxs,
		EnumInfos:         file_ai_v1_common_proto_enumTypes,
		MessageInfos:      file_ai_v1_common_proto_msgTypes,
	}.Build()
	File_ai_v1_common_proto = out.File
	file_ai_v1_common_proto_goTypes = nil
	file_ai_v1_common_proto_depIdxs = nil
}
