// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: ai/v1/tool.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolServiceExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolServiceExecuteRequest) Reset() {
	*x = ToolServiceExecuteRequest{}
	mi := &file_ai_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolServiceExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolServiceExecuteRequest) ProtoMessage() {}

func (x *ToolServiceExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolServiceExecuteRequest.ProtoReflect.Descriptor instead.
func (*ToolServiceExecuteRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_tool_proto_rawDescGZIP(), []int{0}
}

func (x *ToolServiceExecuteRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ToolServiceExecuteRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolServiceExecuteRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ToolServiceExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolServiceExecuteResponse) Reset() {
	*x = ToolServiceExecuteResponse{}
	mi := &file_ai_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolServiceExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolServiceExecuteResponse) ProtoMessage() {}

func (x *ToolServiceExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolServiceExecuteResponse.ProtoReflect.Descriptor instead.
func (*ToolServiceExecuteResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_tool_proto_rawDescGZIP(), []int{1}
}

func (x *ToolServiceExecuteResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolServiceExecuteResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_ai_v1_tool_proto protoreflect.FileDescriptor

const file_ai_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x10ai/v1/tool.proto\x12\x0eflowmind.ai.v1\x1a\x12ai/v1/common.proto\"\x99\x01\n" +
	"\x19ToolServiceExecuteRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.flowmind.ai.v1.RequestContextR\acontext\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"p\n" +
	"\x1aToolServiceExecuteResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.flowmind.ai.v1.ErrorDetailR\x05error2o\n" +
	"\vToolService\x12`\n" +
	"\aExecute\x12).flowmind.ai.v1.ToolServiceExecuteRequest\x1a*.flowmind.ai.v1.ToolServiceExecuteResponseB9Z7ai-flowmind/services/go-api/internal/grpcclient/pb;aiv1b\x06proto3"

var (
	file_ai_v1_tool_proto_rawDescOnce sync.Once
	file_ai_v1_tool_proto_rawDescData []byte
)

func file_ai_v1_tool_proto_rawDescGZIP() []byte {
	file_ai_v1_tool_proto_rawDescOnce.Do(func() {
		file_ai_v1_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_tool_proto_rawDesc), len(file_ai_v1_tool_proto_rawDesc)))
	})
	return file_ai_v1_tool_proto_rawDescData
}

var file_ai_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_v1_tool_proto_goTypes = []any{
	(*ToolServiceExecuteRequest)(nil),  // 0: flowmind.ai.v1.ToolServiceExecuteRequest
	(*ToolServiceExecuteResponse)(nil), // 1: flowmind.ai.v1.ToolServiceExecuteResponse
	(*RequestContext)(nil),             // 2: flowmind.ai.v1.RequestContext
	(*ErrorDetail)(nil),                // 3: flowmind.ai.v1.ErrorDetail
}
var file_ai_v1_tool_proto_depIdxs = []int32{
	2, // 0: flowmind.ai.v1.ToolServiceExecuteRequest.context:type_name -> flowmind.ai.v1.RequestContext
	3, // 1: flowmind.ai.v1.ToolServiceExecuteResponse.error:type_name -> flowmind.ai.v1.ErrorDetail
	0, // 2: flowmind.ai.v1.ToolService.Execute:input_type -> flowmind.ai.v1.ToolServiceExecuteRequest
	1, // 3: flowmind.ai.v1.ToolService.Execute:output_type -> flowmind.ai.v1.ToolServiceExecuteResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_v1_tool_proto_init() }
func file_ai_v1_tool_proto_init() {
	if File_ai_v1_tool_proto != nil {
		return
	}
	file_ai_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_tool_proto_rawDesc), len(file_ai_v1_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_tool_proto_goTypes,
		DependencyIndexes: file_ai_v1_tool_proto_depIdxs,
		MessageInfos:      file_ai_v1_tool_proto_msgTypes,
	}.Build()
	File_ai_v1_tool_proto = out.File
	file_ai_v1_tool_proto_goTypes = nil
	file_ai_v1_tool_proto_depIdxs = nil
}
