// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: ai/v1/vision.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VisionServiceAnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Image         *ImagePart             `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisionServiceAnalyzeRequest) Reset() {
	*x = VisionServiceAnalyzeRequest{}
	mi := &file_ai_v1_vision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisionServiceAnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisionServiceAnalyzeRequest) ProtoMessage() {}

func (x *VisionServiceAnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_vision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisionServiceAnalyzeRequest.ProtoReflect.Descriptor instead.
func (*VisionServiceAnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_vision_proto_rawDescGZIP(), []int{0}
}

func (x *VisionServiceAnalyzeRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *VisionServiceAnalyzeRequest) GetImage() *ImagePart {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *VisionServiceAnalyzeRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type VisionServiceAnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []*ContentPart         `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Usage         *TokenUsage            `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisionServiceAnalyzeResponse) Reset() {
	*x = VisionServiceAnalyzeResponse{}
	mi := &file_ai_v1_vision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisionServiceAnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisionServiceAnalyzeResponse) ProtoMessage() {}

func (x *VisionServiceAnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_vision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisionServiceAnalyzeResponse.ProtoReflect.Descriptor instead.
func (*VisionServiceAnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_vision_proto_rawDescGZIP(), []int{1}
}

func (x *VisionServiceAnalyzeResponse) GetContent() []*ContentPart {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *VisionServiceAnalyzeResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *VisionServiceAnalyzeResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

var File_ai_v1_vision_proto protoreflect.FileDescriptor

const file_ai_v1_vision_proto_rawDesc = "" +
	"\n" +
	"\x12ai/v1/vision.proto\x12\x0eflowmind.ai.v1\x1a\x12ai/v1/common.proto\"\xa0\x01\n" +
	"\x1bVisionServiceAnalyzeRequest\x128\n" +
	"\acontext\x18\x01 \x01(\v2\x1e.flowmind.ai.v1.RequestContextR\acontext\x12/\n" +
	"\x05image\x18\x02 \x01(\v2\x19.flowmind.ai.v1.ImagePartR\x05image\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"\xa6\x01\n" +
	"\x1cVisionServiceAnalyzeResponse\x125\n" +
	"\acontent\x18\x01 \x03(\v2\x1b.flowmind.ai.v1.ContentPartR\acontent\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x120\n" +
	"\x05usage\x18\x03 \x01(\v2\x1a.flowmind.ai.v1.TokenUsageR\x05usage2u\n" +
	"\rVisionService\x12d\n" +
	"\aAnalyze\x12+.flowmind.ai.v1.VisionServiceAnalyzeRequest\x1a,.flowmind.ai.v1.VisionServiceAnalyzeResponseB9Z7ai-flowmind/services/go-api/internal/grpcclient/pb;aiv1b\x06proto3"

var (
	file_ai_v1_vision_proto_rawDescOnce sync.Once
	file_ai_v1_vision_proto_rawDescData []byte
)

func file_ai_v1_vision_proto_rawDescGZIP() []byte {
	file_ai_v1_vision_proto_rawDescOnce.Do(func() {
		file_ai_v1_vision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_vision_proto_rawDesc), len(file_ai_v1_vision_proto_rawDesc)))
	})
	return file_ai_v1_vision_proto_rawDescData
}

var file_ai_v1_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_v1_vision_proto_goTypes = []any{
	(*VisionServiceAnalyzeRequest)(nil),  // 0: flowmind.ai.v1.VisionServiceAnalyzeRequest
	(*VisionServiceAnalyzeResponse)(nil), // 1: flowmind.ai.v1.VisionServiceAnalyzeResponse
	(*RequestContext)(nil),               // 2: flowmind.ai.v1.RequestContext
	(*ImagePart)(nil),                    // 3: flowmind.ai.v1.ImagePart
	(*ContentPart)(nil),                  // 4: flowmind.ai.v1.ContentPart
	(*TokenUsage)(nil),                   // 5: flowmind.ai.v1.TokenUsage
}
var file_ai_v1_vision_proto_depIdxs = []int32{
	2, // 0: flowmind.ai.v1.VisionServiceAnalyzeRequest.context:type_name -> flowmind.ai.v1.RequestContext
	3, // 1: flowmind.ai.v1.VisionServiceAnalyzeRequest.image:type_name -> flowmind.ai.v1.ImagePart
	4, // 2: flowmind.ai.v1.VisionServiceAnalyzeResponse.content:type_name -> flowmind.ai.v1.ContentPart
	5, // 3: flowmind.ai.v1.VisionServiceAnalyzeResponse.usage:type_name -> flowmind.ai.v1.TokenUsage
	0, // 4: flowmind.ai.v1.VisionService.Analyze:input_type -> flowmind.ai.v1.VisionServiceAnalyzeRequest
	1, // 5: flowmind.ai.v1.VisionService.Analyze:output_type -> flowmind.ai.v1.VisionServiceAnalyzeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_v1_vision_proto_init() }
func file_ai_v1_vision_proto_init() {
	if File_ai_v1_vision_proto != nil {
		return
	}
	file_ai_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_vision_proto_rawDesc), len(file_ai_v1_vision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_vision_proto_goTypes,
		DependencyIndexes: file_ai_v1_vision_proto_depIdxs,
		MessageInfos:      file_ai_v1_vision_proto_msgTypes,
	}.Build()
	File_ai_v1_vision_proto = out.File
	file_ai_v1_vision_proto_goTypes = nil
	file_ai_v1_vision_proto_depIdxs = nil
}
